### PR TITLE
Fixed the invite thing + Your messed up code

### PR DESCRIPTION
**Pull request by moyshik7**

### CODE REVIEW

**Comment by moyshik7** [comment]
merge

**Comment by moyshik7** [comment]
merge

**Comment by moyshik7** [comment]
merge

**Comment by moyshik7** [comment]
merge

**Comment by moyshik7** [comment]
merge

**Comment by moyshik7** [comment]
cummon

**Comment by moyshik7** [comment]
do it

**Comment by moyshik7** [comment]
Cute neko

**Comment by Rihimihi** [comment]
Done the merge and here is a girl for you
Girl

**Pull request merged**
